### ISSUE TITLE
hello, can u share your training data

### ISSUE THREAD

**Issue by nhochjkaru** [Riczap/The-Gatherer-Cpp#1]
hello, can u share your training data

**Comment by Riczap** [comment]
> hello, can u share your training data

Sure! I have a Google Drive folder with the training data, it's on the description of the YouTube Showcase, but I can post in on here in the afternoon.

**Comment by Riczap** [comment]
Training data: https://drive.google.com/drive/u/2/folders/17X_f17WpzoxHMURSj5QIZ4lMUWPImf5V
