### ISSUE TITLE
What to do with the paths?

### ISSUE THREAD

**Issue by NaseebTheDev** [Riczap/The-Gatherer-Cpp#2]
Hi!, I'm trying to set this up but I'm curious. What should I do about the hard coded paths in the code?
For example:
`auto result = cv::dnn::readNet("C:/Users/ricza/Documents/YOLO Models/YoloV8/best1.onnx");`

**Comment by NaseebTheDev** [comment]
Can we have access to the onxx files? or how we can setup it up? Please.

**Comment by Riczap** [comment]
> Hi!, I'm trying to set this up but I'm curious. What should I do about the hard coded paths in the code?
> For example:
> `auto result = cv::dnn::readNet("C:/Users/ricza/Documents/YOLO Models/YoloV8/best1.onnx");`
> 
> 

Ohhh yeah, I forgot to make that path "universal" you can just replace that on vs to the path of your own model! I'm also attaching an .onnx model so you can try it, thanks for letting me know!

**Comment by Riczap** [comment]
Done! Uploaded the custom model with the classes text file, it should work if you change the path to the place that you have the main files at.

**Comment by NaseebTheDev** [comment]
Oh you're amazing! Thank you so much!
